@startuml
start

:用户打开任务管理界面;
:选择新建任务;
:输入任务名称和描述;
:设置任务截止日期 (DDL);
:设置任务优先级;

if (是否需要提醒?) then (是)
    :设置提醒时间;
else (否)
endif

while (是否添加标签?) is (是)
  :添加标签;
endwhile (否)



:生成默认时间线（只包含DDL）;
:保存任务信息;

stop
@enduml
